// ─── Generated by npm run setup ─────────────────────────────────────────────
// Review this file carefully before running npm run dev.
// Commit it once you're happy — it's the single source of truth for this client.
//
// DO NOT commit your .env file.

import type { ClientConfig } from './src/types/index.js'

export const config: ClientConfig = {
  client: {
    name: 'Clay Bootcamp',
    website: 'https://www.claybootcamp.com',
    industry: 'GTM Engineering Education & Training',
    targetType: 'individual',
    description:
      'The most intensive 1-on-1 GTM Engineering training program available. Clay Bootcamp offers personalized coaching on real projects using Clay.com and related tools, mentorship from top GTME agency CEOs, and a legendary 300+ member alumni network that helps graduates land jobs, launch agencies, close clients, and find co-founders.',
    valuePropositions: [
      '1-on-1 expert coaching on real projects — not pre-recorded videos or cohort lectures',
      'Trusted by Clay itself (40+ Clay employees trained) and top agencies like The Kiln, Sculpted, and Understory',
      'Lifetime access to a 300+ member private network that actively generates jobs, clients, and co-founder matches',
      'Mentorship from top GTME agency CEOs earning $10MM+ ARR cumulatively — covering sales, pricing, niching, and scaling',
      'Graduates have launched agencies reaching $1MM ARR, $40k MRR, and $20k MRR within months of completing the program',
    ],
  },

  buyerProfiles: [
    {
      role: 'Aspiring GTM Engineer / Career Changer',
      title: [
        'SDR',
        'BDR',
        'Sales Development Representative',
        'Business Development Representative',
        'Account Executive',
        'Sales Rep',
        'Inside Sales',
      ],
      seniority: ['junior', 'mid'],
      triggers: [
        'Expressing frustration with manual prospecting or low comp as an SDR',
        'Posting about wanting to learn Clay or GTM Engineering',
        'Asking how to break into GTM Engineering or get started with Clay',
        'Sharing content about outbound automation or Clay workflows',
        'Mentioning career change or wanting to upskill into tech-adjacent roles',
      ],
    },
    {
      role: 'Freelancer / Aspiring Agency Founder',
      title: [
        'Freelancer',
        'Consultant',
        'Independent Consultant',
        'Growth Consultant',
        'Outbound Consultant',
        'Lead Generation Specialist',
        'GTM Consultant',
      ],
      seniority: ['mid', 'senior'],
      triggers: [
        'Posting about starting a Clay agency or GTME consultancy',
        'Looking for their first Clay or outbound automation clients',
        'Asking about pricing, niching, or scaling a GTME agency',
        'Sharing they quit their job to go freelance in the GTM space',
        'Expressing difficulty finding Clay clients or building a portfolio',
      ],
    },
    {
      role: 'RevOps / Sales Ops Professional',
      title: [
        'RevOps Manager',
        'Revenue Operations',
        'Sales Operations Manager',
        'Marketing Operations',
        'Growth Manager',
        'Demand Generation Manager',
        'GTM Operations',
      ],
      seniority: ['mid', 'senior'],
      triggers: [
        'Company recently purchased or started evaluating Clay',
        'Posting about needing to upskill their team on Clay or outbound automation',
        'Asking about Clay best practices or advanced workflows',
        'Struggling with Clay implementation or looking for Clay training resources',
        'Mentioning they want to become the go-to Clay person at their company',
      ],
    },
    {
      role: 'Existing Agency Owner Adding GTME Services',
      title: [
        'Agency Owner',
        'Agency Founder',
        'CEO',
        'Managing Director',
        'Co-Founder',
      ],
      seniority: ['senior', 'executive'],
      triggers: [
        'Running a marketing or sales agency and considering adding Clay/GTME services',
        'Looking to hire Clay experts or GTM Engineers',
        'Posting about expanding service offerings into outbound automation',
        'Asking about how to add Clay as a service line to their agency',
        'Mentioning client requests for Clay or GTM Engineering work they cannot fulfill',
      ],
    },
    {
      role: 'SaaS Team Lead Seeking Training',
      title: [
        'VP Sales',
        'VP Revenue',
        'Head of Growth',
        'Head of Sales',
        'Director of RevOps',
        'Director of Sales Development',
        'Head of GTM',
      ],
      seniority: ['senior', 'executive'],
      triggers: [
        'Company adopted Clay and needs team upskilling',
        'Posting about building an in-house GTM Engineering function',
        'Looking for Clay training for their revenue team',
        'Mentioning reducing dependency on external agencies for outbound',
        'Hiring for GTM Engineer roles internally',
      ],
    },
  ],

  scoring: {
    qualifyThreshold: 50,
    urgentThreshold: 40,
    urgentSignalCount: 3,
    urgentWindowDays: 7,
    scoringWindowDays: 30,
    requalifyAfterDays: 30,
    deduplicationWindowDays: 7,
  },

  signals: [
    {
      name: 'Wants to Learn Clay',
      description: 'Individual expressing interest in learning Clay.com or asking how to get started',
      searchTerms: [
        'how to learn Clay.com',
        'want to learn Clay tool',
        'getting started with Clay',
        'Clay tutorial beginner',
        'how do I use Clay for outbound',
        'Clay.com learning resources',
        'best way to learn Clay',
        'Clay training program',
        'struggling with Clay',
      ],
      platforms: ['linkedin', 'twitter', 'reddit'],
      weight: 30,
    },
    {
      name: 'GTM Engineering Career Interest',
      description: 'Individual exploring or wanting to break into GTM Engineering as a career',
      searchTerms: [
        'how to become a GTM Engineer',
        'GTM Engineering career',
        'want to be a GTM Engineer',
        'breaking into GTM Engineering',
        'GTM Engineer job',
        'GTME career path',
        'transition to GTM Engineering',
        'what is a GTM Engineer',
        'GTM Engineering skills',
      ],
      platforms: ['linkedin', 'twitter', 'reddit'],
      weight: 35,
    },
    {
      name: 'Starting a Clay Agency',
      description: 'Individual posting about launching or considering a Clay/GTME agency',
      searchTerms: [
        'starting a Clay agency',
        'launching a Claygency',
        'Clay freelance clients',
        'GTME agency',
        'GTM Engineering agency',
        'Clay consulting business',
        'outbound agency Clay',
        'how to start a Clay business',
        'first Clay client',
      ],
      platforms: ['linkedin', 'twitter', 'reddit'],
      weight: 40,
    },
    {
      name: 'SDR Career Frustration',
      description: 'SDRs or BDRs expressing burnout, frustration with manual prospecting, or desire to upskill',
      searchTerms: [
        'tired of being an SDR',
        'SDR burnout',
        'manual prospecting is dead',
        'SDR career change',
        'BDR upskill',
        'SDR to GTM Engineer',
        'hate cold calling want automation',
        'SDR looking for next step',
        'outbound is broken need automation',
      ],
      platforms: ['linkedin', 'twitter', 'reddit'],
      weight: 25,
    },
    {
      name: 'Clay Workflow Struggles',
      description: 'Individual asking for help with Clay workflows, credits, or implementation challenges',
      searchTerms: [
        'Clay workflow help',
        'Clay credits burning too fast',
        'Clay table not working',
        'stuck on Clay build',
        'Clay enrichment issues',
        'need help with Clay',
        'Clay waterfalling problems',
        'Clay HTTP API help',
        'Clay integration issues',
      ],
      platforms: ['linkedin', 'twitter', 'reddit'],
      weight: 25,
    },
    {
      name: 'Outbound Automation Learning',
      description: 'Individual exploring outbound automation tools and seeking education',
      searchTerms: [
        'learn outbound automation',
        'Clay Smartlead workflow',
        'Clay Instantly setup',
        'outbound tech stack',
        'best outbound automation course',
        'personalized outbound at scale',
        'AI outbound prospecting',
        'automated lead generation training',
        'Clay HubSpot integration help',
      ],
      platforms: ['linkedin', 'twitter', 'reddit'],
      weight: 20,
    },
    {
      name: 'Hiring GTM Engineers',
      description: 'Company or individual looking to hire GTM Engineers or Clay experts',
      searchTerms: [
        'hiring GTM Engineer',
        'looking for Clay expert',
        'need Clay specialist',
        'GTM Engineer job posting',
        'hiring for Clay',
        'Clay expert needed',
        'looking for outbound automation specialist',
        'GTME hire',
      ],
      platforms: ['linkedin', 'twitter', 'reddit'],
      weight: 20,
    },
    {
      name: 'Clay Bootcamp Mention or Inquiry',
      description: 'Direct mention of or inquiry about Clay Bootcamp',
      searchTerms: [
        'Clay Bootcamp',
        'Nathan Lippi bootcamp',
        'Clay Bootcamp worth it',
        'Clay Bootcamp review',
        'should I join Clay Bootcamp',
        'Clay Bootcamp cost',
        'Clay Bootcamp experience',
      ],
      platforms: ['linkedin', 'twitter', 'reddit'],
      weight: 45,
    },
    {
      name: 'Agency Scaling Challenges',
      description: 'GTME or outbound agency owners discussing growth challenges',
      searchTerms: [
        'scaling Clay agency',
        'GTME agency pricing',
        'Clay agency first clients',
        'outbound agency scaling',
        'Claygency growth',
        'GTM agency niching',
        'how to price Clay services',
        'Clay agency operations',
      ],
      platforms: ['linkedin', 'twitter', 'reddit'],
      weight: 30,
    },
    {
      name: 'Company Adopted Clay Recently',
      description: 'Individual or team that recently started using Clay at their company',
      searchTerms: [
        'just started using Clay',
        'our team adopted Clay',
        'new to Clay at work',
        'company bought Clay',
        'implementing Clay for our team',
        'Clay onboarding',
        'just signed up for Clay',
        'evaluating Clay for outbound',
      ],
      platforms: ['linkedin', 'twitter', 'reddit'],
      weight: 25,
    },
  ],

  keyPeople: [
    {
      name: 'Nathan Lippi',
      role: 'CEO & Founder',
      platform: 'linkedin',
      profileUrl: 'https://www.linkedin.com/in/nathanlippi/',
      isPrimary: true,
    },
    {
      name: 'Patricia Chu',
      role: 'Head of Operations',
      platform: 'linkedin',
      profileUrl: 'https://www.linkedin.com/in/patricia-chu/',
      isPrimary: false,
    },
    {
      name: 'Tanay Mishra',
      role: 'Head of AI Training',
      platform: 'linkedin',
      profileUrl: 'https://www.linkedin.com/in/tanay-mishra/',
      isPrimary: false,
    },
    {
      name: 'Heather Melton',
      role: 'Head of Community Strategy',
      platform: 'linkedin',
      profileUrl: 'https://www.linkedin.com/in/heather-melton/',
      isPrimary: false,
    },
  ],

  suppressionKeywords: [
    'Clay Bootcamp graduate',
    'Clay Bootcamp alumni',
    'graduated from Clay Bootcamp',
    'Clay Bootcamp student',
    'enrolled in Clay Bootcamp',
    'joined Clay Bootcamp',
    'currently in Clay Bootcamp',
    'completing Clay Bootcamp',
    'Clay Bootcamp mentor',
    'Clay Bootcamp coach',
    'bootcamp 🥾',
    '#GirlsWhoClay',
    'Nathan Lippi 🥾',
    'Clay Bootcamp tribe',
    'I took Clay Bootcamp',
    'my experience at Clay Bootcamp',
    'Clay Bootcamp changed my life',
    'shoutout to Clay Bootcamp',
    'thanks to Clay Bootcamp',
    'hired from Clay Bootcamp',
  ],

  competitors: [
    {
      name: 'Clay University',
      url: 'https://www.clay.com/university',
      differentiator:
        'Clay University is free and self-paced — great for basics, but no 1-on-1 coaching, real project building, private network, or mentorship from agency CEOs',
    },
    {
      name: 'Eric Nowoslawski YouTube / Training',
      url: 'https://www.youtube.com/@EricNowoslawski',
      differentiator:
        'Free YouTube content is helpful for surface-level learning but lacks personalized coaching, accountability, and the career-changing network effect',
    },
    {
      name: 'The Kiln Training',
      url: 'https://www.thekiln.co',
      differentiator:
        'The Kiln is a Clay agency that hires from Clay Bootcamp — they are a partner and employer, not a direct training competitor',
    },
    {
      name: 'Sculpted',
      url: 'https://www.sculpted.com',
      differentiator:
        'Sculpted is a top Clay agency that hires from Clay Bootcamp graduates — they are part of the ecosystem rather than a competing training program',
    },
    {
      name: 'General GTM / Sales Courses',
      url: '',
      differentiator:
        'Generic sales or GTM courses teach theory and frameworks, not hands-on Clay and automation engineering with 1-on-1 expert coaching on real client projects',
    },
    {
      name: 'Self-taught via YouTube / Video Courses',
      url: '',
      differentiator:
        'Multiple graduates report that 6 weeks in Clay Bootcamp exceeded a year of self-study — 1-on-1 coaching with real projects creates breakthroughs videos cannot',
    },
  ],

  outreachSequences: [
    {
      name: 'Aspiring GTME - Career Changer',
      steps: [
        {
          channel: 'linkedin' as const,
          delayDays: 0,
          template: `Hey [firstName] — saw your post about [signalReference].

The GTM Engineering space is exploding right now, and the people getting in early are building careers that didn't exist 18 months ago.

Curious if you've thought about getting structured training on it? A lot of folks in your situation have gone from zero to landing agency jobs or closing their first freelance clients within weeks.

Happy to share what I've seen work if you're interested.`,
        },
        {
          channel: 'email' as const,
          delayDays: 3,
          template: `Subject: [firstName], re: your interest in GTM Engineering

Hi [firstName],

I came across your post about [signalReference] and wanted to reach out.

One thing I've noticed: most people trying to break into GTM Engineering spend months watching YouTube tutorials and still feel stuck. The ones who accelerate fastest do it by building real projects with someone guiding them 1-on-1.

Clay Bootcamp is where 300+ people have done exactly that — many going from SDR or complete beginner to running their own agencies or landing dedicated GTM Engineer roles. Clay itself has trained 40+ employees through the program, and top agencies like The Kiln actively hire from our graduates.

Your first step would be a call with one of our top graduates — not a salesperson, but someone who's been exactly where you are. They'll give you the unfiltered truth.

Would that be worth 20 minutes of your time?

[senderName]`,
        },
        {
          channel: 'email' as const,
          delayDays: 7,
          template: `Subject: Re: [firstName], re: your interest in GTM Engineering

Hi [firstName],

Quick follow-up — wanted to share a concrete example.

Charles Ellenburg was grinding as an SDR doing manual prospecting. After Clay Bootcamp, he landed a role at The Kiln (one of the top Clay agencies) and is now a GTM Engineer at Octave. He called the experience "literally life-changing."

Sarmad Sandeelo had 3 agency job offers by his last week of the program — all from the network.

Not saying your path would look the same, but the pattern is consistent: build real skills with expert guidance, get plugged into the right network, and doors open.

If you're serious about making the move, I'd love to connect you with a graduate who can walk you through their experience.

[senderName]`,
        },
      ],
    },
    {
      name: 'Agency Founder - Scaling or Starting',
      steps: [
        {
          channel: 'linkedin' as const,
          delayDays: 0,
          template: `Hey [firstName] — noticed you're [signalReference].

Building a GTME agency is one of the most exciting opportunities right now, but I've seen a lot of people get stuck on the same things: finding that first client, figuring out pricing, or breaking past a revenue ceiling.

We work with agency founders who are tackling exactly that — with 1-on-1 mentorship from CEOs running $1M+ GTME agencies. Curious if that'd be relevant to where you are right now?`,
        },
        {
          channel: 'email' as const,
          delayDays: 3,
          template: `Subject: Scaling your GTME agency, [firstName]

Hi [firstName],

I saw your post about [signalReference] and it resonated — we hear this a lot from agency founders in the GTM Engineering space.

Clay Bootcamp isn't just a training program — for agency founders, it's a growth accelerator. Here's what I mean:

- Jani Vrancsik joined as one of our first students. A year later: team of 9, 30+ clients including ActiveCampaign and Tabnine, Enterprise Clay Partner status, and past $1MM ARR.
- Adam Andrewjeski found his first paid client through the network within a month of graduating. Now past $40k MRR and scaling.
- Matteo Fois went from just starting out to $20k MRR — and says he wouldn't have gotten his clients without the bootcamp.

The secret sauce? 1-on-1 mentorship from agency CEOs who've already solved the problems you're facing (sales, pricing, niching, hiring), plus a network that actively refers clients to each other.

Your first call would be with a successful graduate who can give you the real picture. Worth a conversation?

[senderName]`,
        },
        {
          channel: 'email' as const,
          delayDays: 7,
          template: `Subject: Re: Scaling your GTME agency, [firstName]

[firstName] — one more thought.

The hardest part of building an agency isn't learning the tools. It's the business side: closing deals, pricing right, picking a niche, and keeping clients happy enough to stay and refer.

That's why we match agency founders with mentors like Alex Fine, Mark Colgan, Kellen Casebeer, and Spencer Tahil — people who've built and scaled agencies in this exact space and can work with you on your specific bottlenecks.

Plus, many top Clay agencies hire directly from our network, so there's a built-in talent pipeline when you're ready to grow your team.

If the timing isn't right now, no worries — but if you're actively building, this is the room you want to be in.

[senderName]`,
        },
      ],
    },
    {
      name: 'RevOps Professional - Company Clay Adoption',
      steps: [
        {
          channel: 'linkedin' as const,
          delayDays: 0,
          template: `Hey [firstName] — saw that [signalReference].

When companies adopt Clay, there's usually one person who becomes the internal expert and drives all the ROI. Being that person is a career-accelerating move.

We've trained RevOps teams at Worldpay, Intercom, and 40+ people at Clay itself. Happy to share how the upskilling typically works if you're interested.`,
        },
        {
          channel: 'email' as const,
          delayDays: 3,
          template: `Subject: Becoming the Clay expert at [companyName]

Hi [firstName],

I noticed [signalReference] — exciting time. Clay is incredibly powerful, but most teams barely scratch the surface without structured guidance.

Clay Bootcamp offers 1-on-1 expert coaching tailored to your actual projects and workflows. We've trained teams at Worldpay, Intercom, and even 40+ employees at Clay itself.

Andrés Solano from Worldpay put it well: "Post-bootcamp, we are able to appropriately scope and deliver meaningful work within Clay." His team went from evaluating to leading real projects.

Jess Bergson, Head of CX at Clay, said working with us in her first two weeks helped her "learn the product 10x faster."

We build around your stack — whether that's HubSpot, Salesforce, Attio, or something else — and coach you on the real projects that matter to your org.

Would it make sense to chat with one of our graduates who went through a similar company upskilling path?

[senderName]`,
        },
        {
          channel: 'email' as const,
          delayDays: 6,
          template: `Subject: Re: Becoming the Clay expert at [companyName]

Hi [firstName],

One thing I should mention — we can also audit your existing setup and help spot high-ROI tweaks that your team might be missing.

Companies often find they're leaving significant pipeline on the table simply because their Clay workflows aren't optimized or they're not using the right enrichment strategies.

If you're interested, the first step is a 20-minute call with a successful graduate who can speak to the experience from a practitioner's perspective — not a sales pitch.

[senderName]`,
        },
      ],
    },
    {
      name: 'Self-Taught Clay User Hitting a Ceiling',
      steps: [
        {
          channel: 'linkedin' as const,
          delayDays: 0,
          template: `Hey [firstName] — saw your post about [signalReference].

I hear this a lot: YouTube and Clay University get you started, but there's a ceiling you hit when you're learning solo. The breakthroughs usually come from building real projects alongside someone who's done it hundreds of times.

We've had 300+ people go through exactly that transition. Happy to connect you with one of them if you want to hear what it's like from the other side.`,
        },
        {
          channel: 'email' as const,
          delayDays: 4,
          template: `Subject: Getting past the Clay learning plateau

Hi [firstName],

Your post about [signalReference] caught my eye because it's one of the most common things we hear.

Douglas Young spent over a year trying to learn Clay on his own. His words: "The progress I made in just six weeks at Clay Bootcamp was significantly greater." He landed a job at a Clay agency within a week of graduating.

The difference isn't secret knowledge — it's having a patient, expert-level coach watching you build and correcting course in real time. Plus a community of 300+ practitioners you can lean on for the rest of your career.

Your first call would be with an actual graduate, not a salesperson. They'll tell you honestly whether it makes sense for where you are.

Worth a conversation?

[senderName]`,
        },
      ],
    },
  ],
};

